### Import Library

In [1]:
import cv2
import numpy as np
import json
import os

%matplotlib inline

### Load Iris Needle Dataset Mask

In [ ]:
# Load COCO File Path
f = open('dataset/iris_neddle_raw_dataset/train_annotations.coco.json', 'r')
data = json.load(f)

In [ ]:
# Define Mask Directory
mask_dir = 'dataset/iris_needle_seg_dataset/mask/'

In [ ]:
# Processing Mask
images = data['images']
annotations = data['annotations']

for image in images:
    mask = np.zeros((image['height'], image['width']))
    for annotation in annotations:
        if annotation['image_id'] == image['id']:
            seg = annotation['segmentation']
            seg = np.array(seg).reshape((-1, 1, 2)).astype(np.int32)
            cv2.fillPoly(mask, [seg], 255)
    cv2.imwrite(mask_dir + image['file_name'], mask)
    print(image['file_name'])

### Load Cataract Dataset Mask

In [ ]:
# Load COCO File Path
f = open('datasets/classification_datasets/cataract_raw_dataset/550_coco_imglab.json', 'r')
data = json.load(f)

In [ ]:
# Define Mask Directory
mask_dir = 'datasets/segmentation_datasets/cataract_seg_dataset/mask/'

In [ ]:
# Processing Mask
images = data['images']
annotations = data['annotations']

for image in images:
    mask = np.zeros((image['height'], image['width']))
    for annotation in annotations:
        if annotation['image_id'] == image['id']:
            seg = annotation['segmentation']
            seg = np.array(seg).reshape((-1, 1, 2)).astype(np.int32)
            cv2.fillPoly(mask, [seg], 255)
    if image['file_name'].endswith('.png'):
        image['file_name'] = image['file_name'].replace('.png', '.jpg')
    cv2.imwrite(mask_dir + image['file_name'], mask)
    print(image['file_name'])

with open('550_coco_imglab_fixed.json', 'w') as json_file:
    json.dump(data, json_file)

### Bitwise Operation for Mask Cataract Dataset

In [2]:
image_paths = []
file_names = []
for root, dirs, files in os.walk("datasets/segmentation_datasets/cataract_seg_dataset/original/"):
    for file in files:
        image_paths.append(os.path.join(root, file))
        file_names.append(file)
print(len(image_paths))
print(image_paths[1])

mask_paths = []
for root, dirs, files in os.walk("datasets/segmentation_datasets/cataract_seg_dataset/mask/"):
    for file in files:
        mask_paths.append(os.path.join(root, file))
print(len(mask_paths))
print(mask_paths[1])

550
datasets/segmentation_datasets/cataract_seg_dataset/original/mild_10.jpg
550
datasets/segmentation_datasets/cataract_seg_dataset/mask/mild_10.jpg


In [5]:
for image, mask, filename in zip(image_paths, mask_paths, file_names):
    x = cv2.imread(image)
    x_mask = cv2.imread(mask, cv2.IMREAD_GRAYSCALE)
    
    result = cv2.bitwise_and(x, x, mask=x_mask)
    
    # cv2.imwrite("datasets/segmentation_datasets/cataract_seg_dataset/blended/" + filename, result)

In [6]:
print(x)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [7]:
print(x_mask)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
